//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treangle_Lad
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreanglIF
    {
        public int ID_Treangle { get; set; }
        public string firsts { get; set; }
        public string seconds { get; set; }
        public string thirds { get; set; }
        public string typess { get; set; }
        public string exception { get; set; }
    }
}
